import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { cn } from "@/lib/utils";
import ConsultancyModal from "@/components/Modals/ConsultancyModal";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MedExpress",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className,"h-screen flex flex-col justify-between")}>
        <Providers>
        <ConsultancyModal/>
        <Header/>
        {children}
        <Footer/>
        </Providers>
      </body>
    </html>
  );
}
